account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from account.views import *
# from django.views.generic import RedirectView
from . import views
# from account.views import (DepositeView,)

# from django_registration.backends.one_step.views import RegistrationView


app_name = "account"

urlpatterns = [
    path('logout',views.logout_view,name='logout'),
	path('signup/', signup, name = 'signup'),
	
    
    path('login/', login_view, name = 'login'),

	path("password-reset/", 
    	PasswordResetView.as_view(template_name='user/password_reset.html'),
    	name="password_reset"),

	path("password-reset/done/", 
		PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), 
		name="password_reset_done"),

	path("password-reset-confirm/<uidb64>/<token>/", 
		PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), 
		name="password_reset_confirm"),

	path("password-reset-complete/", 
		PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), 
		name="password_reset_complete"),

	path('resendOTP', resend_otp),
	# path('followers', followers),
	# path('following', following),
	# path('notifications', notifications),
	# path('notifications/clear', clear_notifications),
	

  
    path('delete_user/<int:pk>/', views.DeleteUser.as_view(), name="delete_user"),


   
]

kisii_champions/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('holiday_off.urls', namespace='home')),
    path('account/',include('account.urls', namespace='login')),
]

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import *


from django.db import models

# from django.contrib.auth.models import User
import datetime as dt
from django.forms import CharField, ModelForm
from django.urls import reverse
# from account.models import Profile


# from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UserChangeForm
# from django.contrib.auth.models import User
from .models import UserProfuile
# from .models import Wallet
from . import models


class DepositForm(forms.ModelForm):
    deposited_amount = forms.DecimalField(widget=forms.TextInput(attrs={'type': 'number'}))

    class Meta:
        model = Wallet
        fields = ['deposited_amount']

    def clean_amount(self):
        amount = self.cleaned_data['deposited_amount']
        # Add any additional validation for the amount if needed
        return deposited_amount



class SignUpForm(UserCreationForm):
    name = forms.CharField(label=("Full Name"))
    username = forms.EmailField(label=("Email"))
    phone_number = forms.CharField(label=("Phone Number"), required=False)
    profile_picture = forms.ImageField(label=("Profile Picture"), required=False)

    class Meta:
        model = User
        fields = ('name', 'username', 'phone_number', 'profile_picture', 'password1', 'password2')


class UserPublicDetailsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['user'].widget.attrs.update({
            'hidden': "hidden"
        })
        
        self.fields['user'].widget.attrs.update({
            'hidden': "hidden"
        })

        self.fields['bio'].widget.attrs.update({
            "rows": "3"
        })

        self.fields['currently_hacking_on'].widget.attrs.update({
            "rows": "2"
        })

        self.fields['currently_learning'].widget.attrs.update({
            "rows": "2"
        })

        self.fields['skills_language'].widget.attrs.update({
            "rows": "2",
            "placeholder": "eg: django, python, java, javascript"
        })

        self.fields['education'].widget.attrs.update({
            "rows": "3"
        })
        self.fields['work'].widget.attrs.update({
            "rows": "3"
        })

    class Meta:
        model = UserProfuile
        fields = "__all__"

class LoginUserForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your username'
        })
        
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your password'
        })
    class Meta:
        fields = ['username', 'password']

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your username'
        })

        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your first name'
        })

        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your last name'
        })

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your email-id'
        })

        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your password'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Confirm your password'
        })
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField(max_length=150)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        
        
class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Old Password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New Passowrd'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Conform new password'}))
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']
        
        
class EditUserProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "Enter uour username"}))
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter your first name"}))

    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter your last name"}))

    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter your last name"}))
    class Meta:
        model = User
        fields = ['username', 'first_name', "last_name", 'email']

kisii_champions/templates/user/admin_page.html
{% extends 'base4.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<style>
    table,
    th,
    td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    
    th,
    td {
        padding: 5px;
        text-align: left;
    }
    
    </style>

<style>
    .button {
      background-color: #4CAF50; /* Green */
      border: none;
      color: white;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 6px;
      margin: 4px 2px;
      cursor: pointer;
    }
    
    .button1 {padding: 10px 24px;}
    
    </style>
<main class="container my-4">
 <!-- my account section start -->
 <section class="my__account--section section--padding">
    <div class="container">
        <p class="account__welcome--text">Hello <strong> {{  user.first_name }} </strong> Welcome to store database!</p>
        <div class="my__account--section__inner border-radius-10 d-flex">
            <div class="account__left--sidebar">
                <h2 class="account__content--title h3 mb-20" style="font-weight: 900;font-size: x-large;">Database</h2>
                <ul class="account__menu">
                    <li class="account__menu--list active"><a href="/add-product">add Product</a></li>
                    <li class="account__menu--list active"><a href="/add-attribute">add Attribute</a></li>
                    <li class="account__menu--list active"><a href="/add-category">add Category</a></li>
                    <li class="account__menu--list active"><a href="/add-brand">add Brand</a></li>
                    <li class="account__menu--list active"><a href="/add-color">add Color</a></li>
                    <li class="account__menu--list active"><a href="/add-size">add Size</a></li>
                    <li class="account__menu--list active"><a href="/add-banner">add Banner</a></li>
                    <li class="account__menu--list active"><a href="/display-product">Product Display + search and Remove</a></li>
                    <li class="account__menu--list active"><a href="/checkout-purchasing"> Shopping cart conversion</a></li>
                    <li class="account__menu--list active"><a href="/data">Data</a></li>
                   
                    <li class="account__menu--list"><a href="{% url 'account:logout' %}">Log Out</a></li>
                </ul>
            </div>
            <div class="account__wrapper">
                <div class="account__content">
                    <div class="row">
                        
                           
                                <table class="table-bordered table">
                                    <thead class="breadcrumb__section" style="background-color: coral;padding-top: 80%;padding-bottom: 0.5%;">
                                        <tr>
                                            <th>Order Number</th>
                                            <th>Total Amount</th>
                                            <th>Paid Status</th>
                                            <th>Order Time</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for order in orders %}
                                        <tr>
                                           <td><strong><a href="{% url 'user_orders_items' order.id %}" class="btn btn-sm btn-dark">{{order.id}}</a></strong></td>
                                            <td>{{order.total_amt|floatformat:2}}</td>
                                            <td>{{order.paid_status}}</td>
                                            <td>{{order.order_dt}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                           
                        
                   
                
           
        
   

<!-- my account section end -->

{% endblock %}

kisii_champions/templates/user/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Forgot Password form using Material Design - Demo by W3lessons</title>
  <!-- CORE CSS-->
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">

<style type="text/css">
html,
body {
    height: 100%;
}
html {
    display: table;
    margin: auto;
}
body {
    display: table-cell;
    vertical-align: middle;
}
.margin {
  margin: 0 !important;
}
</style>
  
</head>

<body class="yellow">


  <div id="login-page" class="row">
    <div class="col s12 z-depth-6 card-panel">
      <form  method="Post">
         {% csrf_token %}
        <div class="row">
          <div class="input-field col s12 center">
            <img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBMd0ISBf73-jNuqHkg0wKyH1wZNtZH_key086YqCk475PiH4c8oXpbmeZF63Jza7iSa-ylLcDq9C_31pLIKZhHIdqmoRCaudPmmQCp4oyO_-2VK4o0T4y61JsR3_IG25NKegvq7MR-TNvosO0ENnO6dV7W20VIGGpFXnH0MQQPsem49eWoxfjrICl7A/w640-h509/Screenshot_20230127-171519_Chrome.jpg" width="350px" alt="" class="responsive-img valign profile-image-login">
            <p class="center login-form-text">Welcome To Bdwin_Online_Shop</p>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>
            <!-- <input class="validate" id="email" type="email"> -->
            <input type="email" name="email" placeholder="Email" autocomplete="email" maxlength="254" class="validate" required="" id="id_email">
            <label for="email" data-error="wrong" data-success="right" class="center-align"></label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <!-- <a href="forgot-password.html" class="btn waves-effect waves-light col s12">Recover my Password</a> -->
            <button type="submit" class="btn waves-effect waves-light col s12">Recover my Password</button>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6 m6 l6">
            <p class="margin medium-small"><a href="{% url 'account:signup' %}">Register Now!</a></p>
          </div>
          <div class="input-field col s6 m6 l6">
              <p class="margin right-align medium-small"><a href="{% url 'account:login' %}">Login</a></p>
          </div>          
        </div>

      </form>
    </div>
  </div>


  <center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Post Page - Responsive -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-5104998679826243"
     data-ad-slot="3470684978"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</center>



  <!-- ================================================
    Scripts
    ================================================ -->

  <!-- jQuery Library -->
 <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!--materialize js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-27820211-3', 'auto');
  ga('send', 'pageview');

</script><script src="//load.sumome.com/" data-sumo-site-id="1cf2c3d548b156a57050bff06ee37284c67d0884b086bebd8e957ca1c34e99a1" async="async"></script>




   <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">
            © 2015 W3lessons.info
            <a class="grey-text text-lighten-4 right" href="http://w3lessons.info">Karthikeyan K</a>
            </div>
          </div>
  </footer>
</body>

</html>

kisii_champions/templates/user/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Forgot Password form using Material Design - Demo by W3lessons</title>
  <!-- CORE CSS-->
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">

<style type="text/css">
html,
body {
    height: 100%;
}
html {
    display: table;
    margin: auto;
}
body {
    display: table-cell;
    vertical-align: middle;
}
.margin {
  margin: 0 !important;
}
</style>
  
</head>

<body class="yellow">
<div id="login-page" class="row">
  <div class="alert alert-success" role="alert">
		<h4 class="alert-heading">Well done!</h4>
		 
			  <p>Password Reset Complete.</p>
	   
		<hr>
    <p class="mb-0"><a href="{% url 'account:login' %}">Login</a> !</p>
		
	  </div>
</div>

  <center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Post Page - Responsive -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-5104998679826243"
     data-ad-slot="3470684978"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</center>



  <!-- ================================================
    Scripts
    ================================================ -->

  <!-- jQuery Library -->
 <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!--materialize js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-27820211-3', 'auto');
  ga('send', 'pageview');

</script><script src="//load.sumome.com/" data-sumo-site-id="1cf2c3d548b156a57050bff06ee37284c67d0884b086bebd8e957ca1c34e99a1" async="async"></script>




   <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">
            © 2015 W3lessons.info
            <a class="grey-text text-lighten-4 right" href="http://w3lessons.info">Karthikeyan K</a>
            </div>
          </div>
  </footer>
</body>

</html>

kisii_champions/templates/user/password_reset_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Forgot Password form using Material Design - Demo by W3lessons</title>
  <!-- CORE CSS-->
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">

<style type="text/css">
html,
body {
    height: 100%;
}
html {
    display: table;
    margin: auto;
}
body {
    display: table-cell;
    vertical-align: middle;
}
.margin {
  margin: 0 !important;
}
</style>
  
</head>

<body class="yellow">


  <div id="login-page" class="row">

	{% if messages %}
	{% for mess in messages %}
	<div class="alert alert-{{mess.tags}}" role="alert">
	  {{mess}}
	</div>
	{% endfor %}
  {% endif %} 
<br>

    <div class="col s12 z-depth-6 card-panel">
      <form  method="Post">
         {% csrf_token %}
        <div class="row">
          <div class="input-field col s12 center">
            <img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBMd0ISBf73-jNuqHkg0wKyH1wZNtZH_key086YqCk475PiH4c8oXpbmeZF63Jza7iSa-ylLcDq9C_31pLIKZhHIdqmoRCaudPmmQCp4oyO_-2VK4o0T4y61JsR3_IG25NKegvq7MR-TNvosO0ENnO6dV7W20VIGGpFXnH0MQQPsem49eWoxfjrICl7A/w640-h509/Screenshot_20230127-171519_Chrome.jpg" width="350px" alt="" class="responsive-img valign profile-image-login">
            <p class="center login-form-text">Welcome To Bdwin_Online_Shop</p>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-action-lock-outline prefix"></i>
            <!-- <input class="validate" id="email" type="email"> -->
			<input type="password" name="new_password1" placeholder="Enter New_Password" autocomplete="new-password" class="textinput textInput" required="" id="id_new_password1">
            <label for="email" data-error="wrong" data-success="right" class="center-align"></label>
          </div>
        </div>

		<div class="row margin">
			<div class="input-field col s12">
				<i class="mdi-action-lock-outline prefix"></i>
			  <!-- <input class="validate" id="email" type="email"> -->
			  <input type="password" name="new_password2" placeholder="Re-Enter New_Password" autocomplete="new-password" class="textinput textInput" required="" id="id_new_password2">
			  <label for="email" data-error="wrong" data-success="right" class="center-align"></label>
			</div>
		  </div>

        <div class="row">
          <div class="input-field col s12">
            <!-- <a href="forgot-password.html" class="btn waves-effect waves-light col s12">Recover my Password</a> -->
            <button type="submit" class="btn waves-effect waves-light col s12">Change Password</button>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6 m6 l6">
           
          </div>
          <div class="input-field col s6 m6 l6">
            
          </div>          
        </div>

      </form>
    </div>
  </div>


  <center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Post Page - Responsive -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-5104998679826243"
     data-ad-slot="3470684978"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</center>



  <!-- ================================================
    Scripts
    ================================================ -->

  <!-- jQuery Library -->
 <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!--materialize js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-27820211-3', 'auto');
  ga('send', 'pageview');

</script><script src="//load.sumome.com/" data-sumo-site-id="1cf2c3d548b156a57050bff06ee37284c67d0884b086bebd8e957ca1c34e99a1" async="async"></script>




   <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">
            © 2015 W3lessons.info
            <a class="grey-text text-lighten-4 right" href="http://w3lessons.info">Karthikeyan K</a>
            </div>
          </div>
  </footer>
</body>

</html>

kisii_champions/templates/user/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!--Hero Section-->
 <div class="hero-section hero-background">
    <h1 class="page-title">Login/Register</h1>
</div>

<!--Navigation section-->
<div class="container">
    <nav class="biolife-nav">
        <ul>
            <li class="nav-item"><a href="index-2.html" class="permal-link">Home</a></li>
            <li class="nav-item"><span class="current-page">Authentication</span></li>
        </ul>
    </nav>
    
</div>

<div class="page-contain login-page">

    <!-- Main content -->
    <div id="main-content" class="main-content">
        <div class="container">

            <div class="row">
              {% if otp %}
              <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom display">
                        <h3 class="float-left">Verify Your Email</h3>

                    <!-- <img src="{% static 'main/img/logo.png' %}" class="logo float-right pt-1" width="25"> -->
                    </legend>
                    <input type="hidden" name="usr" value="{{usr.username}}">
                    <!-- <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">OTP</span>
                      </div>
                      <input type="text" class="form-control" placeholder="Enter Your OTP" aria-label="OTP" aria-describedby="basic-addon1" name = 'otp'>
                    </div> -->
                    
                    <div class="row margin">
                      <div class="input-field col s12">
                        <span class="input-group-text" id="basic-addon1">OTP</span>
                        <!-- <i class="mdi-communication-email prefix"></i> -->
                        <input type="text" class="form-control" placeholder="Enter Your OTP" aria-label="OTP" aria-describedby="basic-addon1" name = 'otp'>
                        <!-- <label for="email" class="center-align">Email</label> -->
                      </div>
                    </div>


                </fieldset>
                <div class="form-grounp">
                    <button class="btn waves-effect waves-light col s12" type="submit">Verify</button>
                    <p>Didn`t Recieve OTP  <small class="float-right text-muted"><i><a href="#" class="text-dark" 
                      onclick="ReSendOTP('{{usr.username}}', 'resendOTPmess')"><i id="resendOTPmess">Resend</i> OTP</a></small></p>

                </div>

            </form>
           {% else %}
                <!--Form Sign In-->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="signin-container">
                        <form action="#" name="frm-login" method="post">
                            {% csrf_token %}
                            <p class="form-row">
                                <label for="fid-name">Username:<span class="requite">*</span></label>
                                <input type="text" name="name" placeholder="Full Names" class="textinput textInput" required="" id="id_name">
                            </p>
                            <p class="form-row">
                                <label for="fid-pass">Email:<span class="requite">*</span></label>
                                <input type="email" name="username" placeholder="Email" autofocus="" class="emailinput" required="" id="id_username">
                            </p>
                            <p class="form-row">
                              <label for="fid-pass">Password:<span class="requite">*</span></label>
                              <input type="password" name="password1" placeholder="Password" autocomplete="new-password" class="textinput textInput" required="" id="id_password1">
                          </p>
                          <p class="form-row">
                            <label for="fid-pass">Retype Password:<span class="requite">*</span></label>
                            <input type="password" name="password2" placeholder="Re-type password" autocomplete="new-password" class="textinput textInput" required="" id="id_password2">
                        </p>


                        
                            <p class="form-row wrap-btn">
                                <button class="btn btn-submit btn-bold" type="submit">Create an account</button>
                                <!-- <input class="btn btn-submit btn-bold" type="submit" value="sign in"> -->
                                <a href="{% url 'account:password_reset' %}" class="link-to-help">Forgot your password</a>
                            </p>
                        </form>
                    </div>
                </div>
                {% endif %}
                <!--Go to Register form-->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="register-in-container">
                        <div class="intro">
                            <h4 class="box-title">Already have an account?</h4>
                            <!-- <p class="sub-title">Create an account with us and you’ll be able to:</p> -->
                            <ul class="lis">
                                <li>Check out faster</li>
                                <li>Save multiple shipping anddesses</li>
                                <li>Access your order history</li>
                                <li>Track new orders</li>
                                <li>Save items to your Wishlist</li>
                            </ul>
                            <a href="{% url 'account:login' %}" class="btn btn-bold">Sign In</a>
                            
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

</div>

{% endblock content %}